CREATE TABLE IF NOT EXISTS friendship_status(
friendship_status_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
status varchar (64)
);

CREATE TABLE IF NOT EXISTS mpa(
mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar (64),
description varchar (255)
);

CREATE TABLE IF NOT EXISTS genres(
genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar (64)
);

CREATE TABLE IF NOT EXISTS films(
film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar (64),
description varchar (255),
release_date timestamp,
duration int,
mpa_id int REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genre(
film_id int NOT NULL REFERENCES films (film_id),
genre_id int NOT NULL REFERENCES genres (genre_id),
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users(
user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar (64),
login varchar (64),
name varchar (64),
birthday timestamp
);

CREATE TABLE IF NOT EXISTS user_friends(
user_id int REFERENCES users (user_id),
friend_id int REFERENCES users (user_id),
friendship_status_id int REFERENCES friendship_status (friendship_status_id),
PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes(
user_id int REFERENCES users(user_id),
film_id int REFERENCES films (film_id),
PRIMARY KEY (user_id, film_id)
);